import type { Metadata } from "next"
import "./globals.css"
import WalletBalance from "@/components/wallet-balance"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <WalletBalance />
        {children}
      </body>
    </html>
  )
}
